version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - whisper
    ports:
      - "8100:8000"
    networks:
      - influx_default
    volumes:
      - ./uploads:/app/uploads
      - ./backend/app:/app
    # Aumenta o timeout do wait-for-it para garantir que whisper suba antes da API
    command: ["/bin/bash", "-c", "./wait-for-it.sh whisper:9000 --timeout=120 --strict -- uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
      - ASR_LANGUAGE=pt
      - ASR_MODEL_PATH=/root/.cache  # Garante uso do cache persistente
    ports:
      - "9000:9000"
    networks:
      - influx_default
    volumes:
      - ./uploads:/data
      - ./cache:/root/.cache
  frontend:
    image: nginx:alpine
    ports:
      - "8083:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro

networks:
  influx_default:
    external: true
