version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartnlp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - influx_default
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    ports:
      - "8100:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./backend/app:/app
    networks:
      - influx_default
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
      - ASR_LANGUAGE=pt
      - ASR_MODEL_PATH=/root/.cache  # Garante uso do cache persistente
    ports:
      - "9000:9000"
    volumes:
      - ./uploads:/data
      - ./cache:/root/.cache
    networks:
      - influx_default
  frontend:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "8083:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - influx_default
volumes:
  pgdata:

networks:
  influx_default:
    external: false
